### ISSUE TITLE
undefined method `configure' for Axe::Cucumber:Module (NoMethodError)

### ISSUE THREAD

**Issue by RamyaAnguraj** [dequelabs/axe-matchers#19]
Am using axe-matchers 1.3.2 , when I do Axe::Cucumber.configure as mentioned in your docs - am running into this issue that NoMethodError. Any help?

**Comment by samjonester** [comment]
I'm sorry to hear about the issue! Would you be able to share a sample project or same code that is causing it? It will help me to solve your issue if you can give me as much information as possible :)

**Comment by RamyaAnguraj** [comment]
I have added gem 'axe-matchers' in my Gemfile.

In env.rb file for cucumbers, I have added this 
require 'axe'
require 'axe/hooks'
require 'axe/cucumber/step_definitions'
Axe::Cucumber.configure do |c|
          # browser object
          c.page = Capybara.current_session.driver
end

**Comment by samjonester** [comment]
Thanks for the extra information. It looks like you've found a typo in the documentation. Thanks :) Do you have any interest in submitting a PR to fix the docs?

The setup you're looking for should be:

``` ruby
require 'axe/cucumber/step_definitions'
Axe.configure do |c|
  # browser object
  c.page = Capybara.current_session.driver
end
```

The extra requires aren't technically necessary, unless you find that it's a hassle to explicitly require them when needed in your step files.

**Comment by RamyaAnguraj** [comment]
Thanks for the update! It works.

**Comment by samjonester** [comment]
Glad to hear it! Just so you know, there are also [example projects](https://github.com/dequelabs/axe-matchers/tree/master/examples) in this repo.
