### ISSUE TITLE
Recommendations for sharing config between Rails and Front end?

### ISSUE THREAD

**Issue by cycomachead** [dequelabs/axe-matchers#25]
We have axe-core running on the front end, along with axe-matchers in CI. Currently, we have two different sets of configuration and two different versions of axe-core.

I'm wondering if there's a way to have axe-matchers use the same script and configuration that we are already loading?

**Comment by WilcoFiers** [comment]
I'm not clear what you are asking. With "script" do you mean the axe-core version? And "configuration" is that what you're passing into `axe.configure`?

**Comment by cycomachead** [comment]
I'm just passing in objects in axe.run. Because we use axe on the front end, we have to maintain two sets of spec configurations which occasionally get out of sync.

**Comment by jasonkarns** [comment]
The Axe configuration in axe-matchers can be loaded from a given yaml file or straight from an attributes hash. If you have an existing configuration file (perhaps in json format or similar that your frontend is using), you can just load that yourself into a hash, and pass it to `Axe::Configuration.from_hash` see https://github.com/dequelabs/axe-matchers/blob/ff6b4df075b47ed1a7eebd99fda9a6226fa7538e/lib/axe/configuration.rb#L41

**Comment by cycomachead** [comment]
Thanks for that.

That makes sense!
