### ISSUE TITLE
Replace named capture groups in Cucumber Regex

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-matchers#31]
As of Cucumber-expression 5.0.14, named capture groups are no longer supported, due to it being buggy in Ruby.  This means that axe-matchers' Cucumber selector will not function with Cucumber 3.1.0. The regex will need to be replace. In the mean time people should stay on Cucumber 3.0.0.

**Comment by WilcoFiers** [comment]
OK, so the problem turned out not to be the named capture groups, just Cucumber-expression mistaking comments for actual parts of the regex.

**Comment by WilcoFiers** [comment]
Ignore the previous. As of Cucumber-expression 5.0.14 axe-matchers is completely broken with Cucumber. I had a 5.0.13, which was running fine with the fix in #32, but .14 is a bust.

**Comment by jkodu** [comment]
Closing, as this issue seems not relevant anymore.

**Comment by rbclark** [comment]
Do you mind clarifying on why this was closed as not relevant anymore? I am still seeing this behavior with axe-matchers on a project after upgrading to Cucumber 3.1.2 during boot of the cucumber test suite.

**Comment by wthegamer** [comment]
I am also running into this with cucumber 3.1.2

**Comment by BillyRuffian** [comment]
Agree, this is issue should be reopened.

**Comment by chhatbarjignesh** [comment]
I am trying to get axe-matchers working with cucumber 3.1.2 and ruby 2.5.1 and running into this error

**Comment by jkodu** [comment]
Ran into what could be a similar issue, hence re-opening this for further investigation.

**Comment by jkodu** [comment]
PR in place https://github.com/dequelabs/axe-matchers/pull/64. Closing issue.
