### ISSUE TITLE
Add a thing for generating changelog

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-matchers#43]
- Change log generation should be automated.

**Comment by stephenmathieson** [comment]
It's ugly, but I've been creating an ephemeral `package.json` file and using [`conventional-changelog-cli`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) to generate `CHANGELOG.md` files in non-Node projects.

**Comment by stephenmathieson** [comment]
I have a solution for this, but will need https://github.com/dequelabs/attest-scripts/issues/11 closed first.

**Comment by jkodu** [comment]
@stephenmathieson 
I was going to look into `ruby`-esque way of getting this done. Are you suggesting, that you are going to take this over?

**Comment by stephenmathieson** [comment]
No, this won't be a "ruby-esque" solution, but a language agnostic solution for all of our products/libraries.

**Comment by jkodu** [comment]
A simple `changelog` npm script exists now, which is used to generate the logs.
