### ISSUE TITLE
Method configure in Axe or Axe::Cucumber.. not found. Can please help ?

### ISSUE THREAD

**Issue by tbutiu** [dequelabs/axe-matchers#5]
Tried 2 cases: 
1: adding gemfile, proper require and the configure params. Failure...
2:  Straight from : unzipping the package, going to examples and running the cucumber in the Watir folder. Failure..

e:\QA\Cucumber\axe-matchers-master\examples\watir>cucumber
undefined method `configure' for Axe:Module (NoMethodError)
e:/QA/Cucumber/axe-matchers-master/examples/watir/features/support/env.rb:10:in
`<top (required)>'
C:/ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_la
nguage.rb:96:in `load'

**Comment by tbutiu** [comment]
also... can be ported to bigger Ruby version? 
trying to rake.. gives this:
e:\QA\Cucumber\axe-matchers-master>bundle install
DL is deprecated, please use Fiddle

[!] There was an error parsing `Gemfile`: There was a LoadError while loading ax
e-matchers.gemspec:
cannot infer basepath from
  e:/QA/Cucumber/axe-matchers-master/axe-matchers.gemspec:2:in `require_relative
'

Does it try to require a relative path? That's been removed in Ruby 1.9.. Bundle
r cannot continue.

 #  from e:/QA/Cucumber/axe-matchers-master/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #  source 'https://rubygems.org'
 #  -------------------------------------------

**Comment by jasonkarns** [comment]
I have a fix for the `configure` error. Release coming soon.

As far as the ruby version, we support 2.0+ (1.9 should also work, but we don't test on it). `require_relative` has not been removed in ruby: (latest 2.3.0 docs: http://ruby-doc.org/core-2.3.0/Kernel.html#method-i-require_relative) What specific version of ruby are you running on?

**Comment by tbutiu** [comment]
ruby 2.0.0p0 (2013-02-24) [i386-mingw32]

thanks, looking forward for it!

**Comment by jasonkarns** [comment]
Fixed by bb1c4c15cfaf98ce25809f8c5919b50f95fa90e8 released as [1.2.1](https://github.com/dequelabs/axe-matchers/releases/tag/v1.2.1)
