### ISSUE TITLE
Get WebDriver must respond to #execute_script

### ISSUE THREAD

**Issue by logicalpath** [dequelabs/axe-matchers#51]
Hi,
I'm testing axe with Selenium/Axe using RSPEC. I'm attempting to construct an axe accessibility RSpec check:
`expect(@lti).to be_accessible.within(iframe: 'tool_content', selectr: 'learn-app--main-content')
`
@LTI is a webdriver instance:
`=> #<LtiA11y:0x00007ff2a22d0180 @driver=#<Selenium::WebDriver::Chrome::Driver:0x66afd90ae96e316 browser=:chrome>>
`
When invoke the expect, I get this message:
```
WebDriverScriptAdapter::WebDriverError:
       WebDriver must respond to #execute_script
```
I'm following the instructions from this page:
https://github.com/dequelabs/axe-matchers#installation
Then for RSpec:
https://github.com/dequelabs/axe-matchers/blob/develop/docs/RSpec.md

Any pointers appreciated. I feel like I may have missed something in my setup
Thanks,
Eddie

<pre>
I'm on MacOS Mohave 10.14.1
<code>
axe-matchers (2.2.1)
Chrome Version 70.0.3538.110
selenium-webdriver (3.14.1, 3.11.0)
rspec (3.8.0, 3.7.0, 3.6.0)
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
</code>
</pre>

**Comment by jkodu** [comment]
Hi @logicalpath 

Thanks for reporting this.
We will do some debugging and get back to you.

**Comment by logicalpath** [comment]
@jkodu I found the issue. When I used @driver instead of @lti, it worked.

```
@lti => #<LtiA11y:0x00007fa96c54a520 @driver=#<Selenium::WebDriver::Chrome::Driver:0x5a1c23aa38b1116a browser=:chrome>>

@driver => #<Selenium::WebDriver::Chrome::Driver:0x5a1c23aa38b1116a browser=:chrome>
```
@lti was a page object model

Thank you for your time.

**Comment by jkodu** [comment]
That is excellent. Thanks @logicalpath.

Closing the issue.
