### ISSUE TITLE
cucumber integration with axe-matchers is broken if you are using cucumber > 2.2

### ISSUE THREAD

**Issue by chhatbarjignesh** [dequelabs/axe-matchers#58]
Looks like the step.rb is using the regex with the name capture groups and cucumber stop supporting the named capture groups and hence cucumber integration with axe-matchers is broken if you are using cucumber > 2.2

https://github.com/cucumber/cucumber/issues/329

<pre>
<code>
class Step
      REGEX = /^

      # require initial phrasing, with 'not' to negate the matcher
      (?-x:the page should(?<negate> not)? be accessible)

      # optionally specify which subtree to check, via CSS selector
      (?-x:;? within "(?<inclusion>.*?)")?

      # optionally specify subtrees to be excluded, via CSS selector
      (?-x:;?(?: but)? excluding "(?<exclusion>.*?)")?

      # optionally specify ruleset via list of comma-separated tags
      (?-x:;? according to: (?<tags>.*?))?

      # optionally specify rules to check as comma-separated list of rule ids
      # in addition to default ruleset or explicit ruleset specified above via tags
      # if the 'only' keyword is supplied, then *only* the listed rules are checked, not *additionally*
      (?-x:;?(?: and)? checking(?<run_only> only)?: (?<run_rules>.*?))?

      # optionally specify rules to skip as comma-separated list of rule ids
      (?-x:;?(?: but)? skipping: (?<skip_rules>.*?))?

      # optionally specify custom options to pass directly to axe-core as a yaml-parsed hash or json string
      (?-x:;? with options: (?<options>.*?))?

      $/x
</code>
</pre>
<pre>
<code>
Named capture groups are not supported. See https://github.com/cucumber/cucumber/issues/329 (Cucumber::CucumberExpressions::CucumberExpressionError)
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/tree_regexp.rb:38:in `block in initialize'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/tree_regexp.rb:17:in `each'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/tree_regexp.rb:17:in `each_with_index'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/tree_regexp.rb:17:in `initialize'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/regular_expression.rb:12:in `new'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/regular_expression.rb:12:in `initialize'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:155:in `new'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:155:in `create_expression'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/step_definition.rb:30:in `new'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:83:in `register_rb_step_definition'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/dsl.rb:31:in `register_rb_step_definition'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/dsl.rb:133:in `register_rb_step_definition'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/axe-matchers-2.3.0/lib/axe/cucumber/step_definitions.rb:3:in `<top (required)>'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/cp74367/Documents/BK/RubymineProjects/BitBucket/ace/powr/features/support/env.rb:38:in `<top (required)>'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:144:in `load_file'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `each'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:272:in `load_step_definitions'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:68:in `run!'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
/Users/cp74367/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
/Users/cp74367/.rbenv/versions/2.5.1/bin/cucumber:23:in `load'
/Users/cp74367/.rbenv/versions/2.5.1/bin/cucumber:23:in `<main>'
</code>
</pre>

**Comment by jkodu** [comment]
PR in place https://github.com/dequelabs/axe-matchers/pull/64, closing issue.

**Comment by chhatbarjignesh** [comment]
Thank you @jkodu
