### ISSUE TITLE
Support for Selenium Cucumber and Grunt

### ISSUE THREAD

**Issue by wangsuse** [dequelabs/axe-matchers#6]
Hi,

We are using aXe-core api to hit our application using phantomJS and it is working perfectly. We have BDD testing in Selenium, Cucumber and Grunt. Does axe-matchers supports this, do you have any documentation for same, i can see only Ruby Rails and Cucumber configuration.

Thanks for help.

**Comment by jasonkarns** [comment]
Are you using Cucumber Ruby or Cucumber JS?

**Comment by wangsuse** [comment]
we are using Cucumber JS.

**Comment by jasonkarns** [comment]
I'm not aware of a package that exposes cucumber step definitions for Cucumber JS at the moment, but someone from @dequelabs/deque-developers  can confirm either way.

**Comment by dylanb** [comment]
We do not yet have a Cucumber JS integration. However, axe-core should be easy to integrate into Cucumber JS. Would you be willing to create an integration?

**Comment by spolamraju** [comment]
We tried to integrate aXe with Cucumber.js. However, we are getting [ReferenceError: window is not defined]. We are not sure how to set the window object. Therefore, it is failing while loading axe core dependency. Can you please help?
 var axe = require('../../pages/axe');

Here is the complete output of Grunt task.


Running "clean:0" (clean) task

Running "clean:1" (clean) task

Running "clean:2" (clean) task

Running "env:l" (env) task

Running "cucumberjs:run" (cucumberjs) task
Feature: Login and Load an Application

  Description: Test the login screen and load an application

  Scenario: Load Application   # features\login.feature:4
error
[ReferenceError: window is not defined]
    Given app page launched # features\step_definitions\loginSteps.js:6

1 scenario (1 passed)
1 step (1 passed)
0m19.636s

**Comment by wangsuse** [comment]
We were able to achieve our goal using axe-builder to run cucumberjs with selenium webdriver.

**Comment by dylanb** [comment]
@wangsuse that is awesome! Could you post an example in the axe-webdriverjs project?

**Comment by wangsuse** [comment]
sure. will create a sample example and post it.

Currently, axe-core is covering 47 ADA use cases as per following readme file.
https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md

Is there a plan to increase it? Is there a way to create custom rules?

**Comment by marcysutton** [comment]
@wangsuse the more [recent code](https://github.com/dequelabs/axe-core) has improvements to rules and a more robust configuration object. Custom rules are more the realm of the Attest product at Deque, but you could do quite a bit with the new `axe.configure` method in the open source axe-core module. 

@spolamraju the window object requirement has been removed so you can more easily integrate with Node.

It will be published to npm in the next week, but you can play with the code on Github now.

**Comment by marcysutton** [comment]
@wangsuse to follow up, we have added more rules since April 2016 and there are more on the way. You can follow along with the progress in the [axe-core repo](https://github.com/dequelabs/axe-core/issues?q=is%3Aopen+is%3Aissue+label%3Arules). 

I'm going to close this, since it sounds like the original need was resolved. We'd still love to see your example, if you get a chance to post it. Thanks for using axe!

**Comment by logicalpath** [comment]
Hi,
I'm testing axe with Selenium/Axe using RSPEC. I'm attempting to construct an axe accessibility RSpec check:

`      expect(@lti).to be_accessible.within(iframe: 'tool_content', selectr: 'learn-app--main-content')
`
@lti is a webdriver instance:
`=> #<LtiA11y:0x00007ff2a22d0180 @driver=#<Selenium::WebDriver::Chrome::Driver:0x66afd90ae96e316 browser=:chrome>>`

That is opening an html file:
`      @lti.navigate_to('file:///' + htmlfile.to_s)
`
Then I switch to an iframe:
`@driver.switch_to.frame('tool_content')`

When I invoke expect, I get this error:

```
     Failure/Error: expect(@lti).to be_accessible.within(iframe: 'tool_content', selector: 'learn-app--main-content')

     WebDriverScriptAdapter::WebDriverError:
       WebDriver must respond to #execute_script
    
```
This script works for checking elements in the iframe, but the error occurs when I add in the axe check. Any pointers appreciated.

Thanks for your time!
Eddie
