### ISSUE TITLE
Malformed Results Cause Errors

### ISSUE THREAD

**Issue by samjonester** [dequelabs/axe-matchers#9]
Malformed results being returned from axe-core cause errors while rendering the failure messages within axe-matchers. The results object is defined in axe-core https://github.com/dequelabs/axe-core/blob/master/doc/API.md#results-object.

Axe-matchers should gracefully handle situations when there is information missing from the audit results.

**Comment by jasonkarns** [comment]
Would love to see a full dump of the results json. This could (potentially) indicate a bug in axe-core's output.
